Repository software-project-yu/WealthTracker-BE, pull requests merged in 2024-11, with the labels that each got.

#33 📕docs:resoures폴더 추가
  .gitignore
  src/main/resources/application.properties
Labels: 📕리드미 수정, 중요도⭐️

#39 👷ci:script변경
  appspec.yml
  build.gradle
  scripts/start.sh
  scripts/stop.sh
Labels: 중요도⭐️⭐️, 👷ci/cd

#22 목표 및 일자별 저축 기능에 관한 CRUD 구현
  src/main/resources/application.properties
Labels: ✨기능, 중요도⭐️⭐️⭐️

#29 🐛fix:날짜 범위 한정
  src/main/java/com/WealthTracker/demo/DTO/LoginRequestDTO.java
  src/main/java/com/WealthTracker/demo/DTO/SignupRequestDTO.java
  src/main/java/com/WealthTracker/demo/DTO/VerificationCodeConfirmDTO.java
  src/main/java/com/WealthTracker/demo/repository/ExpendRepository.java
  src/main/java/com/WealthTracker/demo/service/FeedbackServiceImpl.java
  src/main/resources/application.properties
Labels: ✏️수정, 중요도⭐️

#38 Refact/#21 refactdto value verification
  build.gradle
  src/main/java/com/WealthTracker/demo/DTO/LoginRequestDTO.java
  src/main/java/com/WealthTracker/demo/DTO/SignupRequestDTO.java
  src/main/java/com/WealthTracker/demo/DTO/VerificationCodeRequestDTO.java
  src/main/java/com/WealthTracker/demo/DTO/dailysaving/DailySavingRequestDTO.java
  src/main/java/com/WealthTracker/demo/DTO/income_expend/ExpendCategoryAmountDTO.java
  src/main/java/com/WealthTracker/demo/DTO/income_expend/ExpendRequestDTO.java
  src/main/java/com/WealthTracker/demo/DTO/income_expend/IncomeRequestDTO.java
  src/main/java/com/WealthTracker/demo/DTO/target/TargetRequestDTO.java
  src/main/java/com/WealthTracker/demo/controller/AuthController.java
  src/main/java/com/WealthTracker/demo/error/GlobalExceptionHandler.java
  src/test/java/com/WealthTracker/demo/DTO/SignupRequestDTOTest.java
Labels: ♻️리팩토링, 중요도⭐️

#40 카테고리별 지출 목표 구현
  src/main/java/com/WealthTracker/demo/DTO/category_target/CategoryTargetRequestDTO.java
  src/main/java/com/WealthTracker/demo/DTO/category_target/CategoryTargetResponseDTO.java
  src/main/java/com/WealthTracker/demo/DTO/target/TargetResponseDTO.java
  src/main/java/com/WealthTracker/demo/constants/ErrorCode.java
  src/main/java/com/WealthTracker/demo/controller/CategoryTargetController.java
  src/main/java/com/WealthTracker/demo/controller/TargetController.java
  src/main/java/com/WealthTracker/demo/domain/CategoryTarget.java
  src/main/java/com/WealthTracker/demo/domain/Target.java
  src/main/java/com/WealthTracker/demo/repository/CategoryTargetRepository.java
  src/main/java/com/WealthTracker/demo/service/category_target/CategoryTargetService.java
  src/main/java/com/WealthTracker/demo/service/category_target/CategoryTargetServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/target/TargetService.java
  src/main/java/com/WealthTracker/demo/service/target/TargetServiceImpl.java
  src/main/resources/application.properties
Labels: ✨기능, 중요도⭐️⭐️⭐️

#42 목표 달성률 API 기능 삭제 및 ServiceImpl CustomException 보완
  .github/workflows/gradle.yml
  .github/workflows/wealthtracker-actions.yml
  src/main/java/com/WealthTracker/demo/constants/ErrorCode.java
  src/main/java/com/WealthTracker/demo/controller/TargetController.java
  src/main/java/com/WealthTracker/demo/service/LoginServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/SignupServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/target/TargetService.java
  src/main/java/com/WealthTracker/demo/service/target/TargetServiceImpl.java
Labels: ♻️리팩토링, ✏️수정, 중요도⭐️

#50 🐛fix:회원가입 및 이메일 인증 API 설계 수정
  src/main/java/com/WealthTracker/demo/config/SecurityConfig.java
  src/main/java/com/WealthTracker/demo/constants/ErrorCode.java
  src/main/java/com/WealthTracker/demo/constants/SuccessCode.java
  src/main/java/com/WealthTracker/demo/controller/AuthController.java
  src/main/java/com/WealthTracker/demo/domain/User.java
  src/main/java/com/WealthTracker/demo/domain/VerificationCode.java
  src/main/java/com/WealthTracker/demo/repository/UserRepository.java
  src/main/java/com/WealthTracker/demo/repository/VerificationCodeRepository.java
  src/main/java/com/WealthTracker/demo/service/SignupService.java
  src/main/java/com/WealthTracker/demo/service/SignupServiceImpl.java
Labels: ✏️수정, 중요도⭐️⭐️

#18 Fix/#14 expend income monthlylist
  src/main/java/com/WealthTracker/demo/controller/ExpendController.java
  src/main/java/com/WealthTracker/demo/controller/IncomeController.java
  src/main/java/com/WealthTracker/demo/repository/ExpendRepository.java
  src/main/java/com/WealthTracker/demo/repository/IncomeRepository.java
  src/main/java/com/WealthTracker/demo/service/income_expend/ExpendService.java
  src/main/java/com/WealthTracker/demo/service/income_expend/ExpendServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/income_expend/IncomeService.java
  src/main/java/com/WealthTracker/demo/service/income_expend/IncomeServiceImpl.java
Labels: ♻️리팩토링

#54 🚑hotfix:이메일 유효성 검사 변경
  src/main/java/com/WealthTracker/demo/DTO/LoginRequestDTO.java
  src/main/java/com/WealthTracker/demo/DTO/SignupRequestDTO.java
  src/main/java/com/WealthTracker/demo/DTO/VerificationCodeRequestDTO.java
Labels: 중요도⭐️⭐️⭐️, 🚑핫픽스

#57 🚑hotfix:지출 및 수입 리스트 최신순 반환
  src/main/java/com/WealthTracker/demo/repository/ExpendRepository.java
  src/main/java/com/WealthTracker/demo/repository/IncomeRepository.java
Labels: 중요도⭐️⭐️⭐️, 🚑핫픽스

#59 🚑hotfix:비밀번호 재설정 오류 수정
  src/main/java/com/WealthTracker/demo/DTO/VerificationCodeConfirmDTO.java
  src/main/java/com/WealthTracker/demo/controller/AuthController.java
  src/main/java/com/WealthTracker/demo/service/SignupServiceImpl.java
Labels: 중요도⭐️, 🚑핫픽스

#65 ✨feat:목표 그래프 월별 데이터 API 구현
  README.md
  src/main/java/com/WealthTracker/demo/DTO/LoginRequestDTO.java
  src/main/java/com/WealthTracker/demo/DTO/SignupRequestDTO.java
  src/main/java/com/WealthTracker/demo/DTO/VerificationCodeConfirmDTO.java
  src/main/java/com/WealthTracker/demo/DTO/VerificationCodeRequestDTO.java
  src/main/java/com/WealthTracker/demo/DTO/target/TargetGraphDTO.java
  src/main/java/com/WealthTracker/demo/controller/AuthController.java
  src/main/java/com/WealthTracker/demo/controller/TargetController.java
  src/main/java/com/WealthTracker/demo/repository/ExpendRepository.java
  src/main/java/com/WealthTracker/demo/repository/IncomeRepository.java
  src/main/java/com/WealthTracker/demo/repository/TargetRepository.java
  src/main/java/com/WealthTracker/demo/service/SignupServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/target/TargetService.java
  src/main/java/com/WealthTracker/demo/service/target/TargetServiceImpl.java
  src/main/resources/application.properties
Labels: ✨기능, 중요도⭐️⭐️

#68 ✨feat : 프로필 정보 업데이트 기능 구현
  src/main/java/com/WealthTracker/demo/DTO/target/TargetGraphDTO.java
  src/main/java/com/WealthTracker/demo/constants/ErrorCode.java
  src/main/java/com/WealthTracker/demo/controller/TargetController.java
  src/main/java/com/WealthTracker/demo/controller/UserController.java
  src/main/java/com/WealthTracker/demo/domain/User.java
  src/main/java/com/WealthTracker/demo/repository/TargetRepository.java
  src/main/java/com/WealthTracker/demo/service/UserService.java
  src/main/java/com/WealthTracker/demo/service/UserServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/target/TargetService.java
  src/main/java/com/WealthTracker/demo/service/target/TargetServiceImpl.java
  src/main/resources/application.properties
Labels: ✨기능, 중요도⭐️

#70 ✨feat: 비밀번호 확인 API 추가
  src/main/java/com/WealthTracker/demo/DTO/PasswordConfirmDTO.java
  src/main/java/com/WealthTracker/demo/constants/SuccessCode.java
  src/main/java/com/WealthTracker/demo/controller/AuthController.java
  src/main/java/com/WealthTracker/demo/service/SignupService.java
  src/main/java/com/WealthTracker/demo/service/SignupServiceImpl.java
Labels: ✨기능, 중요도⭐️

#71 🔖release:v 1.0.1
  src/main/java/com/WealthTracker/demo/DTO/PasswordConfirmDTO.java
  src/main/java/com/WealthTracker/demo/constants/SuccessCode.java
  src/main/java/com/WealthTracker/demo/controller/AuthController.java
  src/main/java/com/WealthTracker/demo/service/SignupService.java
  src/main/java/com/WealthTracker/demo/service/SignupServiceImpl.java
Labels: 🔖릴리즈

#74 🐛fix: ErrorCode 수정
  src/main/java/com/WealthTracker/demo/constants/ErrorCode.java
Labels: ✏️수정

#75 ✨feat:Swagger Docs 작성
  src/main/java/com/WealthTracker/demo/controller/AuthController.java
  src/main/java/com/WealthTracker/demo/controller/CategoryTargetController.java
  src/main/java/com/WealthTracker/demo/controller/LoginController.java
  src/main/java/com/WealthTracker/demo/controller/TargetController.java
  src/main/java/com/WealthTracker/demo/controller/UserController.java
  src/main/java/com/WealthTracker/demo/repository/PaymentRepository.java
  src/main/java/com/WealthTracker/demo/service/SignupServiceImpl.java
Labels: ✨기능, 중요도⭐️

#72 ♻️refact:custom Exception 예외처리 강화
  src/main/java/com/WealthTracker/demo/controller/IncomeController.java
  src/main/java/com/WealthTracker/demo/enums/PaymentDetail.java
  src/main/java/com/WealthTracker/demo/error/CustomException.java
  src/main/java/com/WealthTracker/demo/error/GlobalExceptionHandler.java
  src/main/java/com/WealthTracker/demo/repository/IncomeRepository.java
  src/main/java/com/WealthTracker/demo/repository/PaymentRepository.java
  src/main/java/com/WealthTracker/demo/service/FeedbackServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/LoginServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/PaymentServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/SignupServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/UserServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/category_target/CategoryTargetServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/income_expend/ExpendIncomeServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/income_expend/ExpendService.java
  src/main/java/com/WealthTracker/demo/service/income_expend/ExpendServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/income_expend/IncomeServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/target/TargetServiceImpl.java
Labels: ♻️리팩토링, 중요도⭐️⭐️

#77 🐛fix:create, update 반환타입 ResponseEntity<>로 수정
  src/main/java/com/WealthTracker/demo/constants/SuccessCode.java
  src/main/java/com/WealthTracker/demo/controller/CategoryTargetController.java
  src/main/java/com/WealthTracker/demo/service/category_target/CategoryTargetService.java
Labels: ✏️수정, 중요도⭐️

#78 🔖release : v 1.1.0
  .github/workflows/wealthtracker-actions.yml
  src/main/java/com/WealthTracker/demo/DTO/PaymentAmountDTO.java
  src/main/java/com/WealthTracker/demo/DTO/PaymentRequestDTO.java
  src/main/java/com/WealthTracker/demo/DTO/PaymentResponseDTO.java
  src/main/java/com/WealthTracker/demo/constants/ErrorCode.java
  src/main/java/com/WealthTracker/demo/constants/SuccessCode.java
  src/main/java/com/WealthTracker/demo/controller/AuthController.java
  src/main/java/com/WealthTracker/demo/controller/CategoryTargetController.java
  src/main/java/com/WealthTracker/demo/controller/IncomeController.java
  src/main/java/com/WealthTracker/demo/controller/LoginController.java
  src/main/java/com/WealthTracker/demo/controller/PaymentController.java
  src/main/java/com/WealthTracker/demo/controller/TargetController.java
  src/main/java/com/WealthTracker/demo/controller/UserController.java
  src/main/java/com/WealthTracker/demo/domain/Payment.java
  src/main/java/com/WealthTracker/demo/enums/PaymentDetail.java
  src/main/java/com/WealthTracker/demo/error/CustomException.java
  src/main/java/com/WealthTracker/demo/error/GlobalExceptionHandler.java
  src/main/java/com/WealthTracker/demo/repository/ExpendRepository.java
  src/main/java/com/WealthTracker/demo/repository/IncomeRepository.java
  src/main/java/com/WealthTracker/demo/repository/PaymentRepository.java
  src/main/java/com/WealthTracker/demo/service/FeedbackServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/LoginServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/PaymentService.java
  src/main/java/com/WealthTracker/demo/service/PaymentServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/SignupService.java
  src/main/java/com/WealthTracker/demo/service/SignupServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/UserServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/category_target/CategoryTargetService.java
  src/main/java/com/WealthTracker/demo/service/category_target/CategoryTargetServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/income_expend/ExpendIncomeServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/income_expend/ExpendService.java
  src/main/java/com/WealthTracker/demo/service/income_expend/ExpendServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/income_expend/IncomeServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/target/TargetServiceImpl.java
  src/main/resources/application.properties
  src/payment/java/com/WealthTracker/demo/DemoApplicationTests.java
Labels: 중요도⭐️⭐️⭐️, 🔖릴리즈

#81 📕docs:Delete src/payment/java/com/WealthTracker/demo directory
  src/payment/java/com/WealthTracker/demo/DemoApplicationTests.java
Labels: 👷ci/cd
