Repository software-project-yu/WealthTracker-BE, pull requests merged in 2024-12, with the labels that each got.

#84 🐛fix:전체 리스트 금액 리턴 추가
  src/main/java/com/WealthTracker/demo/DTO/income_expend/ExpendIncomeResponseDTO.java
  src/main/java/com/WealthTracker/demo/service/income_expend/ExpendIncomeServiceImpl.java
Labels: 중요도⭐️⭐️⭐️, 🚑핫픽스

#85 ♻️refact:Payment API통신 시 필요 내역 수정
  .github/workflows/wealthtracker-actions.yml
  README.md
  src/main/java/com/WealthTracker/demo/DTO/PaymentRequestDTO.java
  src/main/java/com/WealthTracker/demo/DTO/income_expend/ExpendIncomeResponseDTO.java
  src/main/java/com/WealthTracker/demo/constants/ErrorCode.java
  src/main/java/com/WealthTracker/demo/controller/PaymentController.java
  src/main/java/com/WealthTracker/demo/domain/Payment.java
  src/main/java/com/WealthTracker/demo/repository/PaymentRepository.java
  src/main/java/com/WealthTracker/demo/service/PaymentServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/income_expend/ExpendIncomeServiceImpl.java
  src/main/java/com/WealthTracker/demo/util/CategoryExpendInitializer.java
Labels: ♻️리팩토링, 중요도⭐️⭐️

#86 🔖release:v 1.1.1
  src/main/java/com/WealthTracker/demo/DTO/PaymentRequestDTO.java
  src/main/java/com/WealthTracker/demo/constants/ErrorCode.java
  src/main/java/com/WealthTracker/demo/controller/PaymentController.java
  src/main/java/com/WealthTracker/demo/domain/Payment.java
  src/main/java/com/WealthTracker/demo/repository/PaymentRepository.java
  src/main/java/com/WealthTracker/demo/service/PaymentServiceImpl.java
Labels: 중요도⭐️, 🔖릴리즈

#89 🐛fix:Payment 로직 수정
  src/main/java/com/WealthTracker/demo/DTO/PaymentResponseDTO.java
  src/main/java/com/WealthTracker/demo/controller/PaymentController.java
  src/main/java/com/WealthTracker/demo/repository/PaymentRepository.java
  src/main/java/com/WealthTracker/demo/service/PaymentService.java
  src/main/java/com/WealthTracker/demo/service/PaymentServiceImpl.java
Labels: 🐛버그, 중요도⭐️⭐️⭐️, 🚑핫픽스

#90 🐛fix:Payment 수정API 수정
  src/main/java/com/WealthTracker/demo/service/PaymentServiceImpl.java
Labels: 🐛버그, 중요도⭐️⭐️, 🚑핫픽스

#92 🐛fix:프론트 서버주소 추가
  src/main/java/com/WealthTracker/demo/config/SecurityConfig.java
Labels: ✏️수정, 중요도⭐️⭐️

#93 🚑hotfix:expend 최근 목록 반환 조건 추가
  src/main/java/com/WealthTracker/demo/repository/ExpendRepository.java
  src/main/java/com/WealthTracker/demo/service/income_expend/ExpendServiceImpl.java
Labels: 중요도⭐️⭐️, 🚑핫픽스

#94 hotfix: payment 최근 목록 반환 조건 추가
  src/main/java/com/WealthTracker/demo/DTO/PaymentResponseDTO.java
  src/main/java/com/WealthTracker/demo/constants/ErrorCode.java
  src/main/java/com/WealthTracker/demo/controller/PaymentController.java
  src/main/java/com/WealthTracker/demo/enums/PaymentDetail.java
  src/main/java/com/WealthTracker/demo/repository/PaymentRepository.java
  src/main/java/com/WealthTracker/demo/service/FeedbackServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/LoginServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/PaymentService.java
  src/main/java/com/WealthTracker/demo/service/PaymentServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/SignupServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/UserServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/category_target/CategoryTargetServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/income_expend/ExpendIncomeServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/income_expend/ExpendServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/income_expend/IncomeServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/target/TargetServiceImpl.java
  src/main/resources/application.properties
Labels: 중요도⭐️⭐️, 🚑핫픽스

#96 🚑hotfix:Merge Issue 해결
  src/main/java/com/WealthTracker/demo/DTO/PaymentResponseDTO.java
  src/main/java/com/WealthTracker/demo/constants/ErrorCode.java
  src/main/java/com/WealthTracker/demo/enums/PaymentDetail.java
  src/main/java/com/WealthTracker/demo/repository/PaymentRepository.java
  src/main/java/com/WealthTracker/demo/service/FeedbackServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/LoginServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/PaymentService.java
  src/main/java/com/WealthTracker/demo/service/PaymentServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/SignupServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/UserServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/category_target/CategoryTargetServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/income_expend/ExpendIncomeServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/income_expend/ExpendServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/income_expend/IncomeServiceImpl.java
  src/main/java/com/WealthTracker/demo/service/target/TargetServiceImpl.java
  src/main/java/com/WealthTracker/demo/util/CategoryExpendInitializer.java
  src/main/java/com/WealthTracker/demo/util/VerificationCodeUtil.java
  src/main/resources/META-INF/MANIFEST.MF
  src/main/resources/application.properties
Labels: 🐛버그, 중요도⭐️⭐️⭐️, 🚑핫픽스

#97 🚑핫픽스 : META-INF 파일 삭제 후 재병합
  src/main/resources/META-INF/MANIFEST.MF
Labels: 🚑핫픽스
